-- CREATE DATABASE AUTOMOBILE_DEALER;

-- USE AUTOMOBILE_DEALER;

-- CREATE TABLE BRAND( 
-- 	BID CHAR(3) NOT NULL,
-- 	BRAND_NAME VARCHAR(50) NOT NULL, 
--     ORIGIN VARCHAR(30) NOT NULL, 
--     MODELS INT NOT NULL,
--     PRIMARY KEY (BID)
-- );

-- CREATE TABLE C_DETAILS(
-- 	BID CHAR(3) NOT NULL,
--     BRAND_NAME VARCHAR(50) NOT NULL,
--     C_ID CHAR(3) NOT NULL,
--     CAR_NAME VARCHAR(50) NOT NULL,
--     VARIANT VARCHAR(10) NOT NULL,
--     ENGINE_CAPACITY INT NOT NULL,
--     SEATING_CAPACITY INT NOT NULL,
--     FUEL CHAR(1) NOT NULL,
--     PRIMARY KEY (C_ID),
--     CONSTRAINT BRAND_FK FOREIGN KEY (BID) REFERENCES BRAND(BID)
-- );

-- CREATE TABLE PRICE(
-- 	PR_ID CHAR(3) NOT NULL PRIMARY KEY,
-- 	BID CHAR(3),
--     C_ID CHAR(3) NOT NULL,
-- 	PRICE INT,
--     CONSTRAINT C_FK FOREIGN KEY (C_ID) REFERENCES C_DETAILS(C_ID)
-- );

-- CREATE TABLE EMPLOYEE(
-- E_ID CHAR(3) NOT NULL PRIMARY KEY,
-- EMP_NAME VARCHAR(50) NOT NULL ,
-- SERVICE VARCHAR(50) NOT NULL ,
-- NUMBER VARCHAR(10) NOT NULL
-- );

-- CREATE TABLE CUSTOMER(
-- 	UID VARCHAR(10) PRIMARY KEY NOT NULL,
--     CNAME VARCHAR(50) NOT NULL,
--     ADDRESS VARCHAR(255) NOT NULL,
--     PNUMBER CHAR(10) NOT NULL,
--     SERVICE VARCHAR(10) NOT NULL,
--     EMAIL VARCHAR(255), 
--     C_ID CHAR(3),
-- 	E_ID CHAR(3),
--     CONSTRAINT e_FK FOREIGN KEY (E_ID) references EMPLOYEE(E_ID),
--     constraint cAR_FK FOREIGN KEY (C_ID) REFERENCES C_DETAILS(C_ID)
-- );

-- CREATE TABLE INVOICE(
-- 	INV_ID VARCHAR(10) PRIMARY KEY NOT NULL,
--     UID VARCHAR(10) NOT NULL,
--     NAME VARCHAR(50) NOT NULL,
--     PNUMBER CHAR(10) NOT NULL,
--     TRANSACTION_REF VARCHAR(50) NOT NULL,
--     C_ID CHAR(3) NOT NULL,
--     CONSTRAINT iv_fk1 foreign key (C_ID) REFERENCES C_DETAILS(C_ID),
--     CONSTRAINT iv_fk2 FOREIGN KEY (UID) REFERENCES CUSTOMER(UID)
-- );

-- CREATE TABLE PAYMENT(
-- 	INV_ID VARCHAR(10) NOT NULL,
--     PID CHAR(10) NOT NULL PRIMARY KEY,
--     UID VARCHAR(10) NOT NULL,
--     TRANSACTION_REF VARCHAR(50) NOT NULL,
--     REMARKS VARCHAR(255),
--     CONSTRAINT P_FK1 foreign key (UID) references CUSTOMER(UID),
--     CONSTRAINT P_FK2 FOREIGN key (INV_ID) REFERENCES INVOICE (INV_ID)
-- );