USE AUTOMOBILE_DEALER;

BRAND TABLE

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B01", "BMW", "GERMANY", 3
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B02", "MERCEDES", "GERMANY", 3
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B03", "AUDI", "GERMANY", 3
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B04", "SKODA", "GERMANY", 1
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B05", "VOLVO", "SWEDEN", 2
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B06", "LEXUS", "JAPAN", 1
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B07", "LAND ROVER", "UNITED KINGDOM", 3
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B08", "TOYOTA", "JAPAN", 8
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B09", "HONDA", "JAPAN", 7
    );

INSERT INTO BRAND 
	(BID, BRAND_NAME, ORIGIN, MODELS) 
    VALUES (
	"B10", "FORD", "UNITED STATES", 4
    ); 

CAR DETAILS

INSERT INTO C_DETAILS (
	BID, BRAND_NAME, C_ID, CAR_NAME, VARIANT, ENGINE_CAPACITY, SEATING_CAPACITY, FUEL) 
	VALUES (
		"B01", "BMW", "C01", "BMW 320D", "SPORT", 1995, 5, "P");

PRICE TABLE

INSERT INTO PRICE( 
	PR_ID, BID, C_ID, PRICE) 
    VALUES(
    "P01","B01","C01", 4600000);

EMPLOYEE TABLE

INSERT INTO EMPLOYEE(
	E_ID, EMP_NAME, SERVICE, NUMBER)
    VALUES(
    "E01","VIVEK SINGH","SALES","8454123245");